on:
  workflow_dispatch:

  schedule:
    - cron: "0 12 * * 6"
      timezone: "Asia/Kolkata"

jobs:
   dataset-fetch:
      runs-on: ubuntu-latest
      steps:
        - name: Install kaggle
          shell: python
          run: pip install kaggle
