on:
  workflow_dispatch:

  schedule:
    - cron: "0 12 * * 6"
      timezone: "Asia/Kolkata"

jobs:
   dataset-fetch:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:

        - name: Checkout
          uses: actions/checkout@v5

        - name: Install kaggle
          run: |
               pip install kaggle
               kaggle datasets download -d camnugent/california-housing-prices
          env:
            KAGGLE_API_TOKEN: ${{secrets.KAGGLE_API_TOKEN}}

        - name: upload-artifacts
          uses: actions/upload-artifact@v7
          with:
           name: california-housing-prices
           path: california-housing-prices.zip     

        - name: unzip file
          run: |
               mkdir -p data/california-housing-prices
               unzip -o california-housing-prices.zip -d data/california-housing-prices

        - name: Inspecting files
          run: ls -R data/california-housing-prices      

        - name: Tracking creation of file
          run: git status --short  
        
        - name: inspect repository
          run: |
                 pwd
                 ls -la
                 find . -maxdepth 3 -type f
        - name: configure git 
          run: |
               git config user.name "WeenAIthDev"
               git config user.email "273494684+WeenAIthDev@users.noreply.github.com"

        - name: Check dataset files
          run: |
                echo "Dataset files:"
                find data -type f -print

                echo "Git status:"
                git status --short

                echo "Git tracked files:"
                git ls-files data       

    
        - name: check for changes
          run: | 
               git add data
               git commit -m "Dataset update/adding"
               git push origin main
              

