on:
  workflow_dispatch:

  schedule:
    - cron: "0 12 * * 6"
      timezone: "Asia/Kolkata"

jobs:
   dataset-fetch:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Install kaggle
          run: |
               pip install kaggle
               kaggle datasets download -d camnugent/california-housing-prices
          env:
            KAGGLE_API_TOKEN: ${{secrets.KAGGLE_API_TOKEN}}

        - name: upload-artifacts
          uses: actions/upload-artifact@v7
          with:
           name: california-housing-prices
           path: california-housing-prices.zip     

        - name: unzip file
          run: |
               mkdir -p data/california-housing-prices
               unzip california-housing-prices.zip -d data/california-housing-prices

        - name: Inspecting files
          run: ls -R data/california-housing-prices      
        
        - name: Checkout
          uses: actions/checkout@v5

        - name: Tracking creation of file
          run: git status --short  
        
        - name: inspect repository
          run: |
                 pwd
                 ls -la
                 find . -maxdepth 3 -type f
        - name: configure git 
          run: |
               git config user.name "WeenAIthDev"
               git config user.email "273494684+WeenAIthDev@users.noreply.github.com"

        - name: Commit file 
          run: | 
               git add data

        - name: check for changes
          run: | 
               if git diff --cached --quiet ; then
                 echo "No dataset changed"
               else:
                 echo "Dataset changed"
                 git commit -m "Dataset update/adding"
                 git push
               fi
              
        - name: co     

               
        - name: Tracking creation of file
          run: git status --short  
